//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service.WaterMarkSoap")]
    public interface WaterMarkSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 words 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WaterMarker2", ReplyAction="*")]
        Client.service.WaterMarker2Response WaterMarker2(Client.service.WaterMarker2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WaterMarker2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WaterMarker2", Namespace="http://tempuri.org/", Order=0)]
        public Client.service.WaterMarker2RequestBody Body;
        
        public WaterMarker2Request() {
        }
        
        public WaterMarker2Request(Client.service.WaterMarker2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WaterMarker2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string words;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] img;
        
        public WaterMarker2RequestBody() {
        }
        
        public WaterMarker2RequestBody(string words, byte[] img) {
            this.words = words;
            this.img = img;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WaterMarker2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WaterMarker2Response", Namespace="http://tempuri.org/", Order=0)]
        public Client.service.WaterMarker2ResponseBody Body;
        
        public WaterMarker2Response() {
        }
        
        public WaterMarker2Response(Client.service.WaterMarker2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WaterMarker2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] WaterMarker2Result;
        
        public WaterMarker2ResponseBody() {
        }
        
        public WaterMarker2ResponseBody(byte[] WaterMarker2Result) {
            this.WaterMarker2Result = WaterMarker2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WaterMarkSoapChannel : Client.service.WaterMarkSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaterMarkSoapClient : System.ServiceModel.ClientBase<Client.service.WaterMarkSoap>, Client.service.WaterMarkSoap {
        
        public WaterMarkSoapClient() {
        }
        
        public WaterMarkSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WaterMarkSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaterMarkSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaterMarkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.service.WaterMarker2Response Client.service.WaterMarkSoap.WaterMarker2(Client.service.WaterMarker2Request request) {
            return base.Channel.WaterMarker2(request);
        }
        
        public byte[] WaterMarker2(string words, byte[] img) {
            Client.service.WaterMarker2Request inValue = new Client.service.WaterMarker2Request();
            inValue.Body = new Client.service.WaterMarker2RequestBody();
            inValue.Body.words = words;
            inValue.Body.img = img;
            Client.service.WaterMarker2Response retVal = ((Client.service.WaterMarkSoap)(this)).WaterMarker2(inValue);
            return retVal.Body.WaterMarker2Result;
        }
    }
}
